name: clashking_tracking

services:
  pgsync:
    image: clashking/pgsync:7.2.0
    build:
      context: ./pgsync
      dockerfile: Dockerfile
      args:
        PGSYNC_VERSION: "7.2.0"
        PGSYNC_GIT_REF: d438650e6b6a046505e847a604d5be0e9338f2d6
    container_name: clashking-search-pgsync
    restart: unless-stopped
    command:
      - --config
      - /config/schema.json
      - --daemon
    environment:
      PG_DRIVER: psycopg2
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_SSLMODE: ${PG_SSLMODE}
      ELASTICSEARCH: "true"
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_SCHEME: ${ELASTICSEARCH_SCHEME}
      ELASTICSEARCH_API_KEY_ID: ${ELASTICSEARCH_API_KEY_ID}
      ELASTICSEARCH_API_KEY: ${ELASTICSEARCH_API_KEY}
      ELASTICSEARCH_RAISE_ON_ERROR: "true"
      ELASTICSEARCH_RAISE_ON_EXCEPTION: "true"
      ELASTICSEARCH_STREAMING_BULK: "true"
      ELASTICSEARCH_CHUNK_SIZE: "2000"
      ELASTICSEARCH_MAX_RETRIES: "5"
      REDIS_CHECKPOINT: "true"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: "1"
      REDIS_AUTH: ${REDIS_AUTH}
      SQLALCHEMY_POOL_SIZE: "4"
      SQLALCHEMY_MAX_OVERFLOW: "4"
      NUM_WORKERS: "2"
